# SPDX-FileCopyrightText: 2024 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

openapi: "3.1.0"
info:
  title: uc-hub HTTP API
  description: >
    *uc-hub* is the data communication system in u-OS. This document describes the HTTP API for accessing uc-hub as a consumer.
    <br><br>
    Each participant at uc-hub is either a consumer, a provider or both. A *consumer* can list/get available providers and list/get/update variables published by providers. A *provider* publishes variables to uc-hub.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: Weidmüller Interface GmbH & Co. KG
    url: https://www.weidmueller.com/
    email: oss@weidmueller.com
  version: 0.1.0
servers:
  - url: /uc-hub/api/v1
    description: This product is a HTTP API from uc-hub-api.
    x-internal: false
paths:
  /providers:
    get:
      summary: List providers.
      description: >
        List providers.
      tags:
        - Consumer
      security:
        - OAuth2:
            - browse
      operationId: listProviders
      responses:
        "200":
          description: A list of providers.
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: "#/components/schemas/Provider"
              example:
                - name: providers/web-plc
                  links:
                    variables: /uc-hub/api/v1/providers/web-plc/variables
                - name: providers/sys
                  links:
                    variables: /uc-hub/api/v1/providers/sys/variables
        "400":
          description: Bad request.
        "401":
          $ref: "#/components/responses/401UnauthorizedRead"
        "500":
          $ref: "#/components/responses/500InternalServerError"
  /providers/{provider_name}:
    get:
      summary: Get a single provider by name.
      description: Get a single provider by name.
      tags:
        - Consumer
      security:
        - OAuth2:
            - browse
      operationId: getProvider
      responses:
        "200":
          description: A single provider.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Provider"
              example:
                name: providers/web-plc
                links:
                  variables: /uc-hub/api/v1/providers/web-plc/variables
        "400":
          description: Bad request.
        "401":
          $ref: "#/components/responses/401UnauthorizedRead"
        "404":
          description: Provider not found.
        "500":
          $ref: "#/components/responses/500InternalServerError"
    parameters:
      - $ref: "#/components/parameters/provider_name"
  /providers/{provider_name}/variables:
    get:
      summary: List variable values of a single provider.
      description: >
        List all variable values or a subset of variable values of a single provider with or without variable definitions.
      tags:
        - Consumer
      security:
        - OAuth2:
            - read_variables
      operationId: listVariables
      parameters:
        - $ref: "#/components/parameters/Definition"
        - $ref: "#/components/parameters/Prefixes"
      responses:
        "200":
          description: Variables of a single provider with or without variable definitions.
          content:
            application/json:
              schema:
                type: array
                maxItems: 100000
                items:
                  $ref: "#/components/schemas/Variable"
              examples:
                VariablesWithDefinition:
                  value:
                    - name: gvl/input-1
                      value: true
                      definition:
                        data_type: BOOLEAN
                        access_type: READ_ONLY
                    - name: gvl/output-1
                      value: false
                      definition:
                        data_type: BOOLEAN
                        access_type: READ_WRITE
                Variables:
                  value:
                    - name: gvl/input-1
                      value: true
                    - name: gvl/output-1
                      value: false
        "400":
          description: Bad request.
        "401":
          $ref: "#/components/responses/401UnauthorizedRead"
        "404":
          description: Provider not found.
        "500":
          $ref: "#/components/responses/500InternalServerError"
    post:
      summary: Update variable values of a single provider.
      description: Update all variable values or a subset of variable values of a single provider.
      tags:
        - Consumer
      security:
        - OAuth2:
            - update_variables
      operationId: updateVariables
      requestBody:
        description: The request body contains the variable values which shall be updated.
        required: true
        content:
          application/json:
            schema:
              type: array
              maxItems: 100000
              items:
                $ref: "#/components/schemas/Variable"
              example:
                - name: gvl/input-1
                  value: true
                - name: gvl/output-1
                  value: false
      responses:
        "200":
          description: >
            Ok<br><br>
            Variable write command was successfully send.
            The updated variables are not being returned because the provider may query the write and apply the changes asynchronously. The value write might occur later or could be overridden by another write, thus never being applied.
        "400":
          description: Bad request.
        "401":
          $ref: "#/components/responses/401UnauthorizedWrite"
        "404":
          description: Provider not found.
        "422":
          description: Unprocessable entity. The variables in the request body cannot be processed.
        "500":
          $ref: "#/components/responses/500InternalServerError"
    parameters:
      - $ref: "#/components/parameters/provider_name"
  /providers/{provider_name}/variables/{variable_name}:
    get:
      summary: Get variable value of a single provider.
      description: Get variable value of a single provider with or without variable definition.
      tags:
        - Consumer
      security:
        - OAuth2:
            - read_variables
      operationId: getVariable
      parameters:
        - $ref: "#/components/parameters/Definition"
      responses:
        "200":
          description: A variable value with or without definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variable"
              examples:
                VariableWithDefinition:
                  value:
                    name: gvl/input-1
                    value: true
                    definition:
                      data_type: BOOLEAN
                      access_type: READ_ONLY
                Variable:
                  value:
                    name: gvl/input-1
                    value: true
        "400":
          description: Bad request.
        "401":
          $ref: "#/components/responses/401UnauthorizedRead"
        "500":
          $ref: "#/components/responses/500InternalServerError"
    post:
      summary: Update variable value of a single provider.
      description: Update variable value of a single provider.
      tags:
        - Consumer
      security:
        - OAuth2:
            - update_variables
      operationId: updateVariable
      requestBody:
        description: The request body contains the variable value which shall be updated.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Variable"
            example:
              name: providers/web-plc/variables/gvl/output-1
              value: true
      responses:
        "200":
          description: >
            Ok<br><br>
            Variable write command was successfully send.
            The updated variable is not being returned because the provider may query the write and apply the changes asynchronously. The value write might occur later or could be overridden by another write, thus never being applied.
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 400
                message: "Variable was not updated due to a malformed request."
        "401":
          $ref: "#/components/responses/401UnauthorizedWrite"
        "404":
          description: Variable not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: 404
                message: "Variable was not found."
        "500":
          $ref: "#/components/responses/500InternalServerError"
    parameters:
      - $ref: "#/components/parameters/provider_name"
      - $ref: "#/components/parameters/variable_name"
components:
  parameters:
    provider_name:
      name: provider_name
      in: path
      description: Name of a provider.
      required: true
      schema:
        type: string
        maxLength: 63
        pattern: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$
      example: web-plc
    variable_name:
      name: variable_name
      in: path
      description: Name of a variable.
      required: true
      schema:
        type: string
        maxLength: 1023
        pattern: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?(\/[a-z]([a-z0-9-]{0,61}[a-z0-9])?)*$
      example: gvl/input-1
    Prefixes:
      name: prefixes
      in: query
      description: >
        This parameter is used to filter variables by prefixes. The parameter shall contain a comma-separated list of prefixes. The response will include all variables where the variable name matches one of the given prefixes.
        <br><br>
        The endpoint will filter out duplicates: Each variable will occur only once in the response array.
        <br><br>
        Since the names might contain '/' characters, the parameter needs to be URL-encoded.
      schema:
        type: string
        maxLength: 1023
        format: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?(\/[a-z]([a-z0-9-]{0,61}[a-z0-9])?)*$
      example: gvl,gvl/output-1
    Definition:
      name: definition
      in: query
      description: If true, the response will contain variable definitions.
      schema:
        type: boolean
  responses:
    401UnauthorizedRead:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 401
            message: "You are not authorized to get this resource."
    401UnauthorizedWrite:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 401
            message: "You are not authorized to update this resource."
    500InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 500
            message: "The request was not handled due to an internal server error."
  schemas:
    Duration:
      type: object
      description: A duration between two timestamps.
      properties:
        seconds:
          type: integer
          format: int64
          minimum: -9223372036854776000
          maximum: 9223372036854776000
        nanos:
          type: integer
          format: int32
          minimum: -999999999
          maximum: 999999999
    Error:
      type: object
      properties:
        code:
          type: number
          description: HTTP error status code.
        message:
          type: string
          maxLength: 1023
          format: string
          description: Error message.
      required:
        - code
        - message
    Provider:
      type: object
      properties:
        name:
          description: The relative resource name without the leading slash, e.g. 'providers/web-plc'.
          type: string
          maxLength: 63
          format: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$
        links:
          description: URLs for requesting subresources.
          type: object
          properties:
            variables:
              description: URL for requesting variables of the provider.
              type: string
              maxLength: 2047
              format: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?(\/[a-z]([a-z0-9-]{0,61}[a-z0-9])?)*$
    Timestamp:
      type: object
      description: A timestamp measured by the number of nanoseconds that have elapsed since 00:00:00 UTC on 1 January 1970, which is referred to as the Unix epoch, without adjustments made due to leap seconds.
      properties:
        seconds:
          type: integer
          format: int64
          minimum: -9223372036854776000
          maximum: 9223372036854776000
        nanos:
          type: integer
          format: int32
          minimum: 0
          maximum: 999999999
    VariableAccesstype:
      type: string
      maxItems: 1
      description: Access type of the variable, e.g. READ_ONLY.
      enum:
        - READ_ONLY
        - READ_WRITE
    VariableDatatype:
      type: string
      maxItems: 1
      description: Data type of the variable, e.g. BOOLEAN.
      enum:
        - BOOLEAN
        - DURATION
        - FLOAT64
        - INT64
        - STRING
        - TIMESTAMP
    Variable:
      type: object
      description: A variable containing the name and the actual value.
      properties:
        name:
          type: string
          maxLength: 1023
          format: ^[a-z]([a-z0-9-]{0,61}[a-z0-9])?(\/[a-z]([a-z0-9-]{0,61}[a-z0-9])?)*$
          description: The relative resource name of the variable without the leading slash, e.g. 'providers/web-plc/variables/gvl/input-1'.
        value:
          description: The value of the variable.
          oneOf:
            - type: string
              format: string
              maxLength: 16383
            - type: number
            - type: boolean
            - $ref: "#/components/schemas/Duration"
            - $ref: "#/components/schemas/Timestamp"
        definition:
          $ref: "#/components/schemas/VariableDefinition"
      required:
        - name
        - value
    VariableDefinition:
      type: object
      description: The definition of a variable containing data type and access type.
      properties:
        data_type:
          $ref: "#/components/schemas/VariableDatatype"
        access_type:
          $ref: "#/components/schemas/VariableAccesstype"
      required:
        - data_type
        - access_type
  securitySchemes:
    OAuth2:
      type: oauth2
      description: The HTTP API uses the OAuth2 client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: "tbd"
          scopes:
            browse: Browse available providers and variables.
            read_variables: Read variables.
            update_variables: Update variables.
tags:
  - name: Consumer
    description: >
      A consumer may

      - list/get available providers

      - list/get/update variables published by providers.
