# SPDX-FileCopyrightText: 2025 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

openapi: 3.1.0
info:
  title: Administration API
  description: HTTP API for administrating a u-OS device.
  contact:
    name: Weidmüller
  license:
    name: MIT
    identifier: MIT
  version: 1.1.0
servers:
- url: /u-os-adm/api/v1
paths:
  /logging/entries:
    get:
      tags:
      - logging
      summary: Get all log entries.
      description: The entries can be filtered and accessed via pagination.
      operationId: get_logging_entries
      parameters:
      - name: cursor
        in: query
        description: |-
          The cursor is used to paginate through the log entries.
          It's empty for the first page.
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: |-
          Number of requested entries.
          Default is 100.
        required: false
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: sources
        in: query
        description: |-
          Filter parameter for log sources.
          The exact name of the source must be indicated.
        required: false
        schema:
          type: array
          items:
            type: string
      - name: filter_msgs
        in: query
        description: |-
          Only include log entries whose message contains all filter-strings.
          Not case sensitive. If not set or empty, all messages will be included.
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: Log entries found sucessfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogEntryResponse'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.logging.readonly
  /logging/reports:
    post:
      tags:
      - logging
      summary: Trigger the generation of a report.
      description: |-
        The report will contain the current system logs.
        The report generation is a long-running operation.
        You can poll the status of the operation using the `/operations/{operation_id}` endpoint.
      operationId: create_logging_report
      responses:
        '202':
          description: The generation of the report has been started successfully.
          headers:
            Location:
              schema:
                type: string
              description: URL of the operation resource to poll for status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLogReportResponse'
        '409':
          description: A report generation is already in progress.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.logging.readonly
  /logging/reports/{report_id}:
    get:
      tags:
      - logging
      summary: Get the report by the given report_id.
      description: |-
        The report is a gzipped tar archive containing all system logs.
        You need to trigger the report generation first using the `/logging/reports` endpoint.
      operationId: get_logging_report
      parameters:
      - name: report_id
        in: path
        description: ID of the report to retrieve
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Report found sucessfully
          content:
            application/octet-stream: {}
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.logging.readonly
  /logging/sources:
    get:
      tags:
      - logging
      summary: Get available log sources.
      description: All log sources will be listed here, for examples all systemd services.
      operationId: get_logging_sources
      responses:
        '200':
          description: Log sources retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogSourcesResponse'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.logging.readonly
  /network/config:
    get:
      tags:
      - network
      summary: Get the current network configuration of the device.
      description: This only returns fields that can be configured and changed via the HTTP API.
      operationId: get_network_config
      responses:
        '200':
          description: Network config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkConfig'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.network.readonly
      - OAuth2:
        - u-os-adm.network.readwrite
    put:
      tags:
      - network
      summary: Set the full network configuration of the device.
      description: |-
        This endpoint sets the network configuration of the device. Must include all settings and interfaces.
        Will return the updated configuration on success.
      operationId: set_network_config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkConfig'
        required: true
      responses:
        '200':
          description: Network config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkConfig'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.network.readwrite
    patch:
      tags:
      - network
      summary: Modify the network configuration of the device.
      description: |-
        This endpoint modifies the network configuration of the device by applying a JSON merge patch (https://datatracker.ietf.org/doc/html/rfc7396)
        to the current configuration.
        Will return the updated configuration after applying the patch on success.
      operationId: update_network_config
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateNetworkConfig'
        required: true
      responses:
        '200':
          description: Network config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkConfig'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.network.readwrite
  /network/state:
    get:
      tags:
      - network
      summary: Get the current network state of the device.
      description: This includes properties that can not be configured via the HTTP API, like the current IP addresses and routing table.
      operationId: get_network_state
      responses:
        '200':
          description: Network state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkState'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.network.readonly
      - OAuth2:
        - u-os-adm.network.readwrite
  /openapi.json:
    get:
      tags:
      - openapi
      summary: Get the current API spec
      description: Returns the current OpenAPI specification of the u-OS Admin API. This is useful for clients to discover the API endpoints and their parameters.
      operationId: get_openapi
      responses:
        '200':
          description: OpenAPI specification JSON
          content:
            application/json: {}
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2: []
  /operations/{operation_id}:
    get:
      tags:
      - operations
      summary: Get the status of a long running operation by its ID.
      description: The operation ID can only be retained at the time it is created.
      operationId: get_operation
      parameters:
      - name: operation_id
        in: path
        description: ID of the operation
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Status of the long running operation
          headers:
            Location:
              schema:
                type: string
              description: URL of the created resource as result of the long running operation. This is only the case when the process has been completed and a resource has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationState'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2: []
  /recovery:factory-reset:
    post:
      tags:
      - recovery
      summary: Triggers a factory reset.
      description: Triggers a factory reset, which erases all user data on the system.
      operationId: recovery_factory_reset
      responses:
        '202':
          description: Factory reset initiated successfully.
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.recovery.readwrite
  /security/config:
    get:
      tags:
      - security
      summary: Get the security configuration for the system.
      description: Get the security configuration for the system.
      operationId: get_security_settings
      responses:
        '200':
          description: Security configuration found successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecuritySettings'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.security.readonly
      - OAuth2:
        - u-os-adm.security.readwrite
    put:
      tags:
      - security
      summary: Set the security configuration for the system.
      description: Set the security configuration for the system.
      operationId: set_security_settings
      requestBody:
        description: Security configuration to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecuritySettings'
        required: true
      responses:
        '200':
          description: Security configuration updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecuritySettings'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.security.readwrite
  /system/disks:
    get:
      tags:
      - system
      summary: This endpoint returns disk information
      description: Returns a list of all storage disks in the system and their respective properties.
      operationId: get_system_disks
      responses:
        '200':
          description: Disk information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disks'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.system.readonly
      - OAuth2:
        - u-os-adm.system.readwrite
  /system/info:
    get:
      tags:
      - system
      summary: This endpoint returns static system information (such as cpu architecture, firmware info, ...)
      description: |-
        Some hardware information can only be read out if the device was booted via uboot.
        Everything that could not be determined is returned as None (these information are marked as optional).
      operationId: get_system_info
      responses:
        '200':
          description: System information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemInformation'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.system.readonly
      - OAuth2:
        - u-os-adm.system.readwrite
  /system/nameplate:
    get:
      tags:
      - system
      summary: Returns the digital nameplate information of the device.
      description: Returns nameplate information according to the IDTA digital nameplate specification 3.0.
      operationId: get_system_nameplate
      responses:
        '200':
          description: Nameplate information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceNameplate'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.system.readonly
      - OAuth2:
        - u-os-adm.system.readwrite
  /system:reboot:
    post:
      tags:
      - system
      summary: Triggers a system reboot.
      description: Triggers a reboot. System will be unavailable for a while after triggering this.
      operationId: system_reboot
      responses:
        '202':
          description: System reboot initiated successfully.
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.system.readwrite
  /update/config:
    get:
      tags:
      - update
      summary: Get the update configuration for the system.
      description: The update configuration contains settings related to updating a u-OS device.
      operationId: get_update_settings
      responses:
        '200':
          description: Update configuration found successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSettings'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.update.readonly
      - OAuth2:
        - u-os-adm.update.readwrite
    put:
      tags:
      - update
      summary: Set the update configuration for the system.
      description: |-
        The update configuration contains settings related to updating a u-OS device.
        Updating the configuration will restart the update service to apply new settings.
      operationId: set_update_settings
      requestBody:
        description: Update configuration to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSettings'
        required: true
      responses:
        '200':
          description: Update configuration updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSettings'
        default:
          description: Common HTTP Error codes may be thrown by this method, such as 400, 401, 403, 404, 422 or 500. See body for detailed error info.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpErrorPayload'
      security:
      - OAuth2:
        - u-os-adm.update.readwrite
components:
  schemas:
    AddressInformation:
      type: object
      description: Contains the address information of the device. Part of the device nameplate.
      required:
      - Street
      - Zipcode
      - CityTown
      - NationalCode
      properties:
        CityTown:
          type: string
        NationalCode:
          type: string
        Street:
          type: string
        Zipcode:
          type: string
    CreateLogReportResponse:
      type: object
      required:
      - operation_id
      properties:
        operation_id:
          type: string
          format: uuid
    DeviceNameplate:
      type: object
      description: |-
        Contains the device nameplate information.

        Based on [IDTA 02006-3-0 Digital Nameplate for industrial equipment specification](https://github.com/admin-shell-io/submodel-templates/tree/main/published/Digital%20nameplate/3/0)
      required:
      - URIOfTheProduct
      - ManufacturerName
      - ManufacturerProductDesignation
      - AddressInformation
      - OrderCodeOfManufacturer
      properties:
        AddressInformation:
          $ref: '#/components/schemas/AddressInformation'
        HardwareVersion:
          type:
          - string
          - 'null'
        ManufacturerName:
          type: string
        ManufacturerProductDesignation:
          type: string
        ManufacturerProductType:
          type:
          - string
          - 'null'
        OrderCodeOfManufacturer:
          type: string
        SerialNumber:
          type:
          - string
          - 'null'
        SoftwareVersion:
          type:
          - string
          - 'null'
        URIOfTheProduct:
          type: string
        YearOfConstruction:
          type:
          - string
          - 'null'
    Disk:
      type: object
      required:
      - device_path
      - mount_points
      - file_system
      - total_size
      - free_size
      - storage_type
      properties:
        device_path:
          type: string
        file_system:
          type: string
        free_size:
          type: integer
          format: int64
          minimum: 0
        mount_points:
          type: array
          items:
            type: string
        storage_type:
          $ref: '#/components/schemas/StorageType'
        total_size:
          type: integer
          format: int64
          minimum: 0
    Disks:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Disk'
    Firmware:
      type: object
      required:
      - name
      - version
      properties:
        name:
          type: string
        version:
          type: string
    GlobalDnsServers:
      type: object
      description: |-
        Represents the global DNS servers used by the system.

        The order of the servers represents their priority, with the first one being the primary DNS server unless an interface overrides it.
      required:
      - servers
      - searches
      properties:
        searches:
          type: array
          items:
            type: string
          example:
          - .
        servers:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4String'
    HttpErrorPayload:
      type: object
      description: |-
        Common error payload structure for HTTP responses.

        Based on [RFC 9457](https://datatracker.ietf.org/doc/html/rfc9457)
      required:
      - type
      - title
      - status
      properties:
        detail:
          type:
          - string
          - 'null'
          description: Optional details about the error
          example: 'Low Level OS Error #1234'
        instance:
          type:
          - string
          - 'null'
          format: uri-reference
          description: A human-readable explanation specific to this occurrence of the problem
          example: null
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem
          example: 500
          maximum: 599
          minimum: 100
        title:
          type: string
          description: Human-readable error message.
          example: Something went wrong in the backend.
        type:
          type: string
          format: uri-reference
          description: |-
            A URI reference that identifies the problem type

            The last part of the URI is always a [ErrorId]
          example: /u-os-adm/api/v1/errors/set-security-settings
    InterfaceConfig:
      type: object
      description: Represents the configuration of a single network interface, used for putting.
      required:
      - ipv4_config
      properties:
        ipv4_config:
          $ref: '#/components/schemas/Ipv4Config'
    InterfaceState:
      type: object
      description: Represents the current state of a network interface.
      required:
      - type
      - ipv4
      properties:
        ipv4:
          $ref: '#/components/schemas/Ipv4State'
        type:
          $ref: '#/components/schemas/InterfaceType'
    InterfaceType:
      type: string
      description: The type of network interface.
      enum:
      - ETHERNET
      - USB
    Ipv4Config:
      type: object
      description: Represents the IPv4 configuration of a network interface, used for putting.
      required:
      - dhcp
      - addresses
      - gateway
      - dns
      properties:
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4Subnet'
        dhcp:
          type: boolean
        dns:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4String'
        gateway:
          oneOf:
          - type: 'null'
          - type: string
            format: ipv4
            description: Represents an IPv4 address in a string format.
    Ipv4PrefixLength:
      type: integer
      format: int32
      examples:
      - '24'
      maximum: 32
      minimum: 0
    Ipv4Route:
      type: object
      description: An IP route entry in the IPv4 routing table.
      required:
      - destination
      - gateway
      - interface
      - metric
      properties:
        destination:
          $ref: '#/components/schemas/Ipv4Subnet'
        gateway:
          $ref: '#/components/schemas/Ipv4String'
        interface:
          type: string
          example: eth-x4
        metric:
          type: integer
          format: int32
          example: 103
          minimum: 0
    Ipv4State:
      type: object
      description: Represents the IPv4 state of a network interface.
      required:
      - activated
      properties:
        activated:
          type: boolean
          description: Activated is true when the connection is active and a cable is plugged in. Otherwise false.
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4Subnet'
    Ipv4String:
      type: string
      format: ipv4
      description: Represents an IPv4 address in a string format.
    Ipv4Subnet:
      type: object
      description: |-
        Ipv4 address with prefix length.

        The prefix length is used to determine the network mask.
      required:
      - ip
      - prefix_length
      properties:
        ip:
          $ref: '#/components/schemas/Ipv4String'
        prefix_length:
          $ref: '#/components/schemas/Ipv4PrefixLength'
    LogEntry:
      type: object
      required:
      - timestamp
      - message
      - source
      properties:
        message:
          type: string
          example: Log message
        source:
          $ref: '#/components/schemas/LogSource'
        timestamp:
          type: string
          format: date-time
    LogEntryResponse:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LogEntry'
        next_cursor:
          type:
          - string
          - 'null'
    LogSource:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          example: u-os-adm
    LogSourcesResponse:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LogSource'
    Memory:
      type: object
      required:
      - total_size
      - available_size
      properties:
        available_size:
          type: integer
          format: int64
          minimum: 0
        total_size:
          type: integer
          format: int64
          minimum: 0
    NetworkConfig:
      type: object
      description: Used for writing the network configuration. All fields are required to be present, but can be empty in some cases.
      required:
      - hostname
      - interfaces
      properties:
        hostname:
          type: string
          format: hostname
          example: wm-uc20-m3000
          maxLength: 63
          minLength: 1
        interfaces:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InterfaceConfig'
          propertyNames:
            type: string
          example:
            eth-x4:
              ipv4_config:
                addresses:
                - ip: 192.168.1.102
                  prefix_length: 24
                dhcp: false
                dns:
                - 8.8.8.8
                gateway: 192.168.1.1
            eth-x5:
              ipv4_config:
                addresses: []
                dhcp: true
                dns: []
                gateway: null
    NetworkState:
      type: object
      description: |-
        The current network state on the device.

        Note that this may differ from the configuration, e.g. a DHCP interface has an address in the state, but not in the configuration.
      required:
      - dns_resolver
      - routes
      - interfaces
      properties:
        dns_resolver:
          $ref: '#/components/schemas/GlobalDnsServers'
        interfaces:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InterfaceState'
          propertyNames:
            type: string
          example:
            eth-x4:
              ipv4:
                activated: true
                addresses:
                - ip: 192.168.1.100
                  prefix_length: 24
              type: ETHERNET
            eth-x5:
              ipv4:
                activated: true
                addresses:
                - ip: 192.168.1.101
                  prefix_length: 24
              type: ETHERNET
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4Route'
    OperationState:
      oneOf:
      - $ref: '#/components/schemas/OperationStatePending'
      - $ref: '#/components/schemas/OperationStateCompleted'
      - $ref: '#/components/schemas/OperationStateFailed'
      description: Represents the entire state of a long-running operation.
    OperationStateCompleted:
      type: object
      required:
      - status
      - created_at
      - completed_at
      properties:
        completed_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        resource_id:
          type: string
        resource_url:
          type: string
          format: url
        status:
          type: string
          enum:
          - COMPLETED
    OperationStateFailed:
      type: object
      required:
      - status
      - created_at
      - failed_at
      properties:
        created_at:
          type: string
          format: date-time
        failed_at:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - FAILED
    OperationStatePending:
      type: object
      required:
      - status
      - created_at
      properties:
        created_at:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - PENDING
    SecuritySettings:
      type: object
      required:
      - root_access
      properties:
        root_access:
          type: object
          required:
          - enabled
          properties:
            enabled:
              type: boolean
    StorageType:
      type: string
      enum:
      - Internal
      - Removable
    SystemInformation:
      type: object
      required:
      - cpu_architecture
      - firmware
      - memory
      properties:
        cpu_architecture:
          type: string
        firmware:
          $ref: '#/components/schemas/Firmware'
        memory:
          $ref: '#/components/schemas/Memory'
    UpdateInterfaceConfig:
      type: object
      description: Represents the configuration of a single network interface, used for patching.
      required:
      - ipv4_config
      properties:
        ipv4_config:
          $ref: '#/components/schemas/UpdateIpv4Config'
    UpdateIpv4Config:
      type: object
      description: Represents the IPv4 configuration of a network interface, used for patching.
      properties:
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4Subnet'
        dhcp:
          type: boolean
        dns:
          type: array
          items:
            $ref: '#/components/schemas/Ipv4String'
        gateway:
          oneOf:
          - type: 'null'
          - type: string
            format: ipv4
            description: Represents an IPv4 address in a string format.
    UpdateNetworkConfig:
      type: object
      description: Allows partial updates to the network configuration via patch requests.
      properties:
        hostname:
          type: string
          format: hostname
          example: wm-uc20-m3000
          maxLength: 63
          minLength: 1
        interfaces:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UpdateInterfaceConfig'
          propertyNames:
            type: string
          example:
            eth-x4:
              ipv4_config:
                dhcp: false
                gateway: null
            eth-x5:
              ipv4_config:
                dhcp: true
    UpdateSettings:
      type: object
      description: Represents the update configuration for the system used in get and put.
      required:
      - signed_update
      properties:
        signed_update:
          type: object
          required:
          - enabled
          properties:
            enabled:
              type: boolean
              description: True if signed updates are enabled, false otherwise.
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth2/token
          scopes:
            u-os-adm.logging.readonly: Read access for logging endpoints
            u-os-adm.network.readonly: Read access for network endpoints
            u-os-adm.network.readwrite: Read and write access for network endpoints
            u-os-adm.recovery.readwrite: Read and write access for recovery endpoints
            u-os-adm.security.readonly: Read access for security endpoints
            u-os-adm.security.readwrite: Read and write access for security endpoints
            u-os-adm.system.readonly: Read access for system endpoints
            u-os-adm.system.readwrite: Read and write access for system endpoints
            u-os-adm.update.readonly: Read access for update endpoints
            u-os-adm.update.readwrite: Read and write access for update endpoints
      description: The HTTP API uses the OAuth2 client credentials flow.
tags:
- name: logging
  description: Centralized system logging, capture and reporting API for u-OS
- name: network
  description: API for network settings and state of u-OS
- name: openapi
  description: API for reading the OpenAPI specification
- name: operations
  description: API for u-OS long running operations
- name: recovery
  description: API for recovery of u-OS
- name: security
  description: API for u-OS security settings
- name: system
  description: API for general system informations & actions of u-OS
- name: update
  description: API for u-OS update settings
